---
title: "Problem Set 3"
---

:::{.callout-important}
Due September 22nd at 10:30 am on Canvas
:::

Problem Set 3 is posted on Canvas. You must use the provided RMarkdown file to complete this problem set.

- Use the RMarkdown file provided (.Rmd extension) and write your answers and code in the spaces provided. Submit the PDF that is "knitted" (1 file).^[This route requires a few more tools. You need to install [RMarkdown](https://rmarkdown.rstudio.com/lesson-1.html) and [TinyTeX](https://yihui.org/tinytex/). The upside? You can produce beautiful documents that show your code and output.]

If you have any issues using RMarkdown please see me in my office so we can make sure you can knit the file on your computer.

### Files

1. [Problem Set - PDF](https://agnesscott.instructure.com/files/584567/)
2. [RMardown file](https://agnesscott.instructure.com/files/584566/)



## Purpose

This third problem set will help you practice:

1. Setting the working directory
2. Loading data into R
3. Computing and interpreting the mean of a variable for different subsets of a sample
4. Estimating the average treatment effect for a randomized experiment


You will use the following commands:

```{r, eval=FALSE}

# From the previous problem sets
setwd()

read.csv()

mean()

# New in this problem set

# Subsetting data; for example:
data$var1[data$var2==1]


```



## Criteria for success

In addition to providing the correct code and/or answer, a successful problem set will:

1. Have clear explanations that demonstrate your knowledge of the material
2. Use the "comment out" function to explain what the code is doing



